name = "telegram-image-hosting"
compatibility_date = "2025-02-23"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "app_data"
id = "854f6bfe607b4b509c5849c18413a590"
preview_id = "69088be9ba19400983d1b14e3e74ecf5"

[env.production]
vars = { NODE_ENV = "production" }
kv_namespaces = [
  { binding = "app_data", id = "854f6bfe607b4b509c5849c18413a590" }
]

[env.preview]
vars = { NODE_ENV = "development" }
kv_namespaces = [
  { binding = "app_data", id = "69088be9ba19400983d1b14e3e74ecf5" }
]
